- action: 
    task: lifter
    position: 0.0,0.5,1.0
- action: 
    task: lifter
    position: 0.0,0.9,0.5
- action: 
    task: lifter
    position: 0.1,0.8,0.5
- action: 
    task: lifter
    position: -0.1,0.8,0.5
- action: 
    task: end
