- action: 
    task: lifter
    position: 0.0,0.5,0.5
- action: 
    task: lifter
    position: 0.25,0.711,0.6
- action: 
    task: lifter
    position: 0.1,0.8,1.0
- action: 
    task: lifter
    position: 0.0,0.857,1.0
- action: 
    task: lifter
    position: 0.0,0.5,0.5
- action: 
    task: lifter
    position: 0.0,0.857,0.5
- action: 
    task: lifter
    position: 0.1,0.8,1.0
- action: 
    task: lifter
    position: 0.204,0.711,0.6
- action: 
    task: lifter
    position: 0.0,0.5,0.5
- action: 
    task: end
