- motion: 
    action: move
    place: 0
- motion: 
    action: lifter
    position: 0,-0.4,3000
- motion: 
    action: wait
    time: -1
- motion: 
    action: lifter
    position: 0,0,3000
- motion: 
    action: end
