- action: 
    task: lifter
    position: 0.0,0.6,0.5
- action: 
    task: lifter
    position: 0.24,0.65,0.4
- action: 
    task: lifter
    position: 0.1,0.8,0.4
- action: 
    task: lifter
    position: 0.0,0.857,0.2
- action: 
    task: end
